name: BuyFoodNow

on:

  schedule:

    - cron: "0 7 * * *"

  workflow_dispatch:

jobs:

  remind:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:

          python-version: "3.11"

      - run: pip install requests

      - run: python bot.py

        env:

          8829249920:AAHeSCWXDJXdKgqfVO0zuh5iMtNxKHmpQRo: ${{ secrets.BOT_TOKEN }}

          616872473: ${{ secrets.CHAT_ID }}
