name: BuyFoodNow

on:

  schedule:

    - cron: "0 7 * * *"

  workflow_dispatch:

jobs:

  remind:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:

          python-version: "3.11"

      - run: pip install requests

      - run: python bot.py

        env:

          BOT_TOKEN: ${{ secrets.8829249920:AAHeSCWXDJXdKgqfVO0zuh5iMtNxKHmpQRo }}

          CHAT_ID: ${{ secrets.616872473 }}
